### ISSUE TITLE
[FR] Clarify roadmap / what's currently supported or add examples

### ISSUE THREAD

**Issue by Diniboy1123** [quic-go/connect-ip-go#35]
Hi,

I am really glad I found a library on the internet that seems to initiate a move upon implementing such a great protocol. I am mainly interested in the client as I would like to connect to a remote MASQUE `connect-ip` server and turn it into a tun interface. But so far there is no documentation, I am guessing this library is still under heavy work.

I have tried to see from the tests and integrations whether it would be feasible to accomplish my goal, but I didn't have luck getting it up and running besides the initial 200 response upon connecting.

What's the current state? I see that the Request struct has no fields atm...

Thanks!

**Comment by marten-seemann** [comment]
Glad you find the library useful. We're very close to a v0.1, the only thing that's missing is writing up some documentation for [quic-go.net](https://quic-go.net).

>  I would like to connect to a remote MASQUE connect-ip server and turn it into a tun interface

That's pretty much what we're doing in the integration test.

> What's the current state? I see that the Request struct has no fields atm...

It doesn't need to, since we're (currently) not supporting IP flow forwarding (see [section 8.3](https://datatracker.ietf.org/doc/html/rfc9484#name-ip-flow-forwarding) of the RFC).

**Comment by Diniboy1123** [comment]
Thanks, I will see if I can get it working then.
